Squashed 'thirdparty/fmt/' changes from 130cf54cb..71144eeaf
71144eeaf implement year_month_day (#3913)
843e29356 Bump github/codeql-action from 3.24.6 to 3.24.9 (#3915)
f5ec5ada2 Update syntax.rst
3b5f3de3b Make CMake version message less confusing (#3907)
ca9193983 Replace std::fill_n with fmt::detail::fill_n (#3909)
74a187288 Implemented fmt::day, fmt::month, fmt::year and related unit tests (#3906)
88620e53a Range formatting documentation  (#3905)
5d63e87d2 Add a formatter for float128
aecec01b3 Initial support for extended FP types
5af88653e Cleanup
45b772f85 Improve std::complex formatter to be compatible with P2197R0 (#3900)
53347891c Make line buffering test less flaky
38881e5ac Fix handling of the fileno macro
6c7cc6a06 Fix group_digits for negative integers (#3901)
365c3fbd2 Bump timeout
c0dac8398 Use p2197 format for complex by default
bb882c03b Simplify path formatting
12acd7988 Fix ambiguous call
c710bfa10 Apply clang-format
73f2b344b Add std::complex formatter
9f3fc6e38 Add XChar support into nested_formatter
c17816cb4 Fix invalid fmt::formatter<>::format return type (#3895)
df6e7b22f Fix relative path for cmake in usage doc (#3890)
c816fa675 Fix a warning
e281749c5 Simplify range formatter
11f2f30f0 Simplify range formatter
13cfaa2ab Guard against usage of _isatty when header was not included (#3880)
0861db500 Support character range formatting  (#3863)
dfe5b12c0 Update os-test.cc (#3883)
09935d823 Bump github/codeql-action from 3.23.2 to 3.24.6 (#3876)
3bc6cc1e6 Protect against locking formatters
4fcc317dc Bump actions/upload-artifact from 4.3.0 to 4.3.1 (#3875)
ae1e93d34 Fix warning C4702 emitted from format.h (MSVC) (#3866)
f68f452de Workaround an ld warning on macOS
ebea5736a Fix chrono locale format bug for RHEL gcc (#3859)
ddf0b7d2b Fix warning C4365 emitted from printf.h (#3865)
0166f455f std.h c++23 build fix (#3856)
8e42eef49 Don't error on min time_point
91b30e5b4 More API details
7a63e233d Readd core.h to headers
44c3fe1eb Fix handling of static separator
ae181cc93 C++23 compatibility: basic_string_view cannot be constructed from nullptr (#3846)
3a6fb2fca Fix some typos. (#3843)
087950479 Fix typo in typename. `containter_type` -> `container_type`. (#3844)
34f415b56 Fix %S formatting for chrono durations with leading zeroes  (#3814)
e17bc6754 Make scan variadic
06311ed1c Fix fixed rounding around zero in Dragon
e5bab8dab added formatter for std::expected (#3834)
9f5f39cb5 Bump actions/upload-artifact from 4.0.0 to 4.3.0 (#3837)
ea581437e Bump github/codeql-action from 2.22.5 to 3.23.2 (#3836)
6321a97d6 Simplify color formatting
4b6b32f38 Deprecate wide stream function
1b54ba4b9 Fix UB in format_arg_store implementation. (#3833)
71a4a8d47 Really fix MSVC warning about <bit> only being available in C++20. (#3832)
8e62172ab Fix a warning
28afff363 Improve buffering
af44c2974 Separate buffer initialization from flush
a1e1eedbb Minor cleanup
ffce3632b Add glibc stream support
b5669512b Don't hang on test failure
6435b169e Add support for line buffering
6f260455a Add scan_data::make_args
e1832bcf0 Consider ADL begin() and end() when joining ranges (#3824)
2caf1b3b9 scan more
668fe2653 doc: fix the chrono %C example value (#3822)
06fc25f26 Don't always enable typeid usage under msvc (#3821)
11ba1270a Fix flush
4c5b4af04 Improve name argument validation
2eb363297 Fix custom formatter example (#3820)
0147e0822 Document println
6b68dff90 Write directly to a stream buffer
b2cde48de Reduce usage of float_specs
8510838db Make format_specs not depend on code unit type
090ee1359 Pass char type to write
470c4e6ca Fix scope for glibc ext for sec, min, and hour (#3812)
13ec66bf7 🛠 Add basic array safety functions and backwards-compatible result type (#3805)
64091b7a2 Fix naming
e95482353 Make fill independent on code unit type
f80a2bee1 Update README.md
83652dfee Restrict always inlining to the top-level API
d249fd9f8 Workaround for gcc 6 (#3810)
73d91351b Mark `iterator_buffer` move constructors as `noexcept`. (#3808)
fe0d910a7 Replace multiple error reporting mechanisms with report_error
f9294f0e6 Improve handling of format specs
c98a5a599 Remove unnecessary checks
5f30d3710 Update README.md
3647feaad Improve scan
e420a58f2 Improve scan prototype
ca37503f9 scan -> scan_to
123e058eb Improve scan prototype
f924d20db core-test -> base-test
d70729215 Fix constness
362b40c1a Fix docs
56fa4d61f Fix docs
cacdf1439 Remove nonstandard alias
4d766b167 Invert dependencies
c10859f15 Remove deprecated options
d0963d482 Make ranges only depend on fmt/base.h
da0f84c42 Cleanup copy functions and move to base.h
59baac522 Remove unused functions
21b045829 Use std::allocator_traits (#3804)
df6a3564b Fix MSVC warning: "The contents of <bit> are available only with C++20 or later." (#3807)
7c163acfd Fix conversion warning in filesystem::path formatter (#3806)
1b55d1030 Update api.rst
5d9d376d4 Update api.rst
6064b85c1 Update api.rst
deb584c0e Update build.py
297b22f58 Remove <memory> dependency
3c9608416 Remove redundant detection of experimental string_view
0cdee904a Add a missing num_bits specialization
7e58af4ea Fix an ICE on clang <= 15
f1924d326 Cleanup macros
52174953b Cleanup conseval detection
b71d98774 Reduce usage of FMT_COSTEXPR20
810d1750f Cleanup constexpr detection
170ffb1ff Simplify constexpr checks
e470ba8b7 Simplify exception detection
bf98e3e4c Cleanup macros
fd87a23d3 Reduce memory dependency
b71ef65b6 Remove iterator dependency
c5340539f Remove unnecessary trait specialization
971f7ae76 Minor cleanup
6159e2b0a Bazel support: Switch to globbing to collect header files
da7a232b9 Cleanup contexts
2595bf57b Fix formatting of ranges with begin()&/end()&
6f5d53ce0 Add fmt::is_contiguous<std::basic_string<Char, Traits, Allocator>>
961df829b Fix buffer overflow if output iterator is std::back_insert_iterator and value is escaped (debug format)
401f08739 Fix write_uintptr_fallback
725992928 Update build.py
3d84b45a2 Update core.h
4331abed2 Move fmt::format to fmt/format.h
fc8f6ba93 Separate compilation for println
58a6bd48a Add core.h for compatibility
79f1506fe Add base.h
4d616479b Simplify make_format_args
cf8426cf8 Sort links on fmt/std.h section
e915d5216 Update api.rst with support provided by std.h
7ba642054 Optimize debug codegen
97867e279 Extend Bazel build support to bzlmod (#3792)
8875cf96c Fix spelling: othewise ==> otherwise (#3791)
f7ed65fa4 Simplify format_arg_store
f34f31b32 Move format_arg_store to detail
fb66131ef Improve arg storage
6af30d8f7 Remove legacy workaround
c177324ba Simplify basic_format_args
545d37a8b Remove extra level of indirection when building args
9f73e45ca Update README.md
a5ae9ae19 Split standard context into a separate class and optimize
23e8109d8 Remove buffer_appender
679af1f5c Remove redundant get_container
48d7fb265 Merge back_insert_iterator and appender
f348d1a21 Reintroduce back_insert_iterator detection
df67df7b4 Add is_back_insert_iterator
17f79ac6c Minor cleanup
dbdfc99fa Don't crash if flush fails during unwinding
c1d9e8840 Remove unnecessary final and apply clang-format
7d73ef85f Cleanup ranges
ae9b0b521 Disable transitive includes
f73388f1a Update README.md
08878044c Update readme
1b7d9db0c Remove string dependency
0641b844a Cleanup string traits
1e938dda2 Simplify char_t
2e5b14bf6 Add compile-time checks to color formatting
e0b604beb Remove a redundant function
6c617c967 Update documentation (#3789)
bee495c97 Remove dead code
794e1b614 Remove redundant overload
c7061776a Bump version
dc52d176d Cleanup dependencies
0e3e61cc0 Remove limits dependency
800a0bb23 Remove dependency on string_view
f2e43f967 Remove char_traits dependency
c9287eb9f Reduce char_traits usage
61f144bd6 Move copy_str for format.h
4687f8e37 Remove dependency on <iterator>
f2c55f6bb Remove dependency on back_insert_iterator
c9d233c0a Decouple appender from back_insert_iterator
242bcaec0 Update README.md (#3784)
4e43a4699 Clarify why we can't have nice things
c36ed77ff Get rid of addressof
e2ab9ab22 Add FMT_GLIBCXX_RELEASE
0378d171f Replace remove_cvref_t with remove_const_t
baea8f690 Update docs
eedfdb4c5 Fix docs
5dbd7fd77 Switch to bootstrap 4 because 5 breaks menus
7fd180268 Fix FMT_OS definition (#3783)
63ce17085 Replace virtual dispatch with normal functions in buffers
74ffea0dc Simplify to_ascii
6c3b2d491 Fix constness
4ec9c2906 Apply coding conventions
f4a7d40dc Dedup throw_format_error
9659f22d3 Don't include os.cc in the module if it is disabled via FMT_OS
068bf9bad Make visitation compatible with std::format
50565f985 Move misplaced join overloads to fmt/ranges.h
0b39d6710 Remove detail::error_handler
c14238503 Improve the pipe API
398ddb8fe Don't include fmt/os.h in the module if it is disabled via FMT_OS
583729493 Remove duplicate version
6c5bcca81 Fix the release script
67c0c0c09 Update version
051b31531 Fix changelog update
b0569451a Bump version
ce3161887 Add overflow check
1a95e5d1b Update changelog
e1aac4266 Implement hex specifier
1705600be Remove optional
0c345dccd Bump actions/upload-artifact from 3.1.2 to 4.0.0 (#3782)
d33731d20 Implement empty format specs
c068c7c62 Add sentinel support
13fa26745 Update changelog
ebd5c8f99 Consistently use `fmt::` when invoking `format_to`. (#3779)
f5ca178c1 Complete scan_handler
138a64bfb Privatization
a5bacf3fe Remove custom_formatter
4aa24f54c Implement visitor for scan
e33c1568c Implement scan argument access
23826669c Cleanup error handling
8e6b2541a Apply coding conventions
4939d67a8 Cleanup scripts
bd3273021 Update release script
5f9058dbd Improve scripts
28576b060 Workaround github markdown mess
5ddd0cad1 Add a visitor for scan arguments
41d31512b Remove unused import
44b76d88f Fix docs
3324152db Update the release script
55190dadb Cleanup chrono test
63e4b93cf Update changelog
c64edcd32 Fix grammar
8c520b4fd Fix comment
2e6bb706b Update changelog
a13d1b12e Update changelog and docs
47a0eec2e Remove unnecessary alias
a8bed3895 Update changelog
e206043d2 Update changelog
4a6f0be5b Improve scan test
662d78415 Fix scan test
d5823aae3 Ceci n'est pas une pipe
d83c1b8d4 Add initial specifier support to scan
bfba2f9e9 Improve iterator handling in scan
a3bf40838 Initial range support in scan
ea1066bbe Cleanup test
be57ec7ec Fix chrono-test on platforms with 32-bit time_t
305747d44 Update changelog
47c8f63d0 Remove redundant specifier
76e8f1040 Update changelog
18ca2248d Document '?'
3a25a5848 Update README.md
4cbf6182e Remove peek
88d19f5de Cleanup scan
62529aad1 Apply coding conventions
df62c8678 Mark grow as deprecated
eef6dbafb Refactor file layer in scan
41c243335 clang-format
0a9d08fef Simplify fallback
e450b7aeb Implement locking
c5a85f8d7 Handle end of input in scan
1fd093add Update changelog
c4f2de493 Improve scan
d06921d8d Update changelog
fc0f84d29 Move formatbuf to ostream.h
86f2ec5de Fix a warning
a537c39fd Move conjunction to where it is used
7c240d52c Remove unused symbol
f64a6a2ec Update changelog
6f9a81678 Enable test
e7875ae0f Fix formatting of some nested ranges
3eb3aef57 Fix handling of set_debug_format
56d7a8c15 Simplify test
968fb9d16 Update changelog
b5f6b36b0 Update changelog
44dd6c0e0 Add glibc support to scan
3a0f4af4e Refactor file layer
1ca1a4a7a Update scan test
dbd9c89b3 Fix URI
9cd2b87e1 Fix wchar_t to char conversion warnings (#3764)
d5da9cc40 Apply clang-tidy
3a2c50d4a Cleanup test
18c43a214 Cleanup test
6b07fff0d Make hex float test more stable on different libc (#3762)
9165434e5 Enable consteval in MSVC VS2019 version 16.10 (#3757)
b8f81dede [StepSecurity] ci: Harden GitHub Actions (#3759)
923005bd4 Add stdlib version check for C++20 (#3754)
afa85e46c Apply clang-format
6025bd7c3 Add localized formatting to non-decimal presentation types of ints (#3750)
5471a2426 Update README.md
7d757cba5 CI: add lint github workflow for running clang-format (#3749)
6855bd532 Apply clang-format
bbee75357 Make clang-format happy
89860eb90 Use void(*)(void*) instead of decltype(&std::free) to satisfy clang in CUDA mode (#3751)
274ba2645 allow format_as() to format reference (#3739)
9048add99 Report out-of-range errors in chrono
640e0c02d Update README.md
6392dba21 Fix warning: identifier '_a' preceded by whitespace in a literal operator declaration is deprecated (#3748)
9a6fd11a5 Fix typo in gmock-gtest-all.cc (#3747)
dee0dbf07 Update README.md
2fabb43b9 Fix README file table (#3744)
9c3c107c8 Fix compile with GCC 6.3.0 (bug #3738) (#3743)
4497a2d09 fix cmake build
81629e425 Convert README to Markdown
6f95000b7 Update README.rst (#3737)
573d74395 error on bool arg w/ char pres_type (#3734)
5d55375a8 Experiment with scan buffering
71bd51e6c Implement `%j` specifier for `std::chrono::duration` (#3732)
f57508924 Simplify test
99b9fbf8e Add formatter for std::source_location (#3730)
8f83ee2ad Apply coding conventions
2a8a69446 Clarify that mixing code unit types is deprecated
04718008a Minor cleanup
b87ea22e2 Add native and generic representation for filesystem::path format spec (#3729)
5cfd28d47 Experiment with FILE in scan
73fae91e6 Cleanup .gitignore
6988be387 Bump version
2d1e4bb35 Remove a useless comment
7f8d41911 Fix overflow in time_point formatting with large dates (#3727)
ccc9ab7bf Include correct header
c4283ec47 Fix a libc++ warning and move the test to the right place
c3f9a7344 Apply coding conventions
06f1c0d72 Clarify that calling non-const format is deprecated
ffa5b14fe Make gtest-extra-test more portable
bea7ecc71 Disable locale-specific tests on OpenBSD
8a3938851 Fix the default locale in ostream_formatter
dd6f657a7 Remove this-> from decltype (#3723)
c13753a70 Fix handling of invalid Unicode in precision
864a8b5f3 fix: support optional<T> with format_as(T) (#3713)
649fe0fc8 Fix handling of null strings with the s specifier
45e124ee4 Added workaround for old xcode compiler bug (#3716)
045b05d79 Revert CMake changes
ec628561c Fix formatting
cbb18c237 Add support for CMake 3.28 C++  modules (#3679)
6b0082e6c Improve OpenBSD workaround
52a99a67f Set PDB path for Visual Studio (#3702)
4548d1eae Make write_escaped_path more portable
050d41e85 Make get_path_string more portable
1c023c008 Update bootstrap
b35d4e40f fix: use FMT_HAS_INCLUDE instead of __has_include
acaf83f40 feat: enable building with gcc 4.8
05aa78377 feat: include xlocale.h only if exists
05dda9490 Bump ossf/scorecard-action from 2.2.0 to 2.3.1 (#3697)
caf4fcb20 Bump github/codeql-action from 2.21.5 to 2.22.5 (#3696)
e0d3e346d Wrap Char in array to avoid pointer arithmetic (#3695)
19276d732 Fix an inconsistentcy between to_string and format
2a2c6e676 Fix flushing C++ iostreams before calling write_console() (#3689)
3b7f58a8b add buffer flush before direct write
e9bbd4069 Update README.rst
857cce7a8 Update README.rst
081d5b0d8 Update README.rst
baae1ed65 add meson instructions to usage docs (#3677)
2ac6c5ca8 Fix error C2668 on Windows with option /std:c++latest (#3680)
d9063baf2 Fix perf regression in ostream::print
f7542c576 Apply clang-format

git-subtree-dir: thirdparty/fmt
git-subtree-split: 71144eeaff2199dbf70a2dc1675f21c731da47f7