Squashed 'thirdparty/pycapnp/' changes from ae965128d..1fb168796
1fb168796 Prepare for v2.0.0 release
1f2349ab4 Update README.md
84830d635 Prepare for v2.0.0b2 release
3aade70bf Some fixes to the magic import system
b6ea909e9 Corner case for cancelled server methods that raise exceptions
0ec4d0b77 Allow cancellation of all capability contexts
49bda5cca Fix re-raising of KjException
ef5e03906 Support `_DynamicListReader` in `_setDynamicField`
aafec2281 Make `reraise_kj_exception` available to downstream
42665a61c Properly join list of methods in _DynamicCapabilityClient
c9bea05f4 DynamicCapabilityClient: fix crash due to wrong types
7a4970605 Disable the use of ninja for windows builds
ca8d12090 Handle exceptions from server callbacks
09f7cd0d0 Unlock the GIL for all capnp functions that do IO
a30fd77a1 Fix retransmit bug for large messages causing message corruption
302a96d84 Update documentation to async code (#331) (#332)
144638663 Make a server fail early when the KJ loop is not running
cc088211d Delete and update some Python 3.7-specific todo notes
b22763f3c Fix 'AttributeError: '_UnixSelectorEventLoop' object has no attribute 'call_soon'

git-subtree-dir: thirdparty/pycapnp
git-subtree-split: 1fb168796d622e1cd19b2353a43ef5bb0b15d5a1